In [1]:
# IMPORTING THE REQUIRED LIBRARIES 

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import geopandas as gpd
from shapely import wkt
pd.set_option('display.max_columns', None)

In [2]:
import cartoframes
from cartoframes.auth import set_default_credentials
from cartoframes.viz import Map, Layer, popup_element, size_bins_style

In [92]:
# PEDESTRIAN DATA FROM CITYIQ API

ped_data = pd.read_csv('vehicle_count_sample.csv')

In [93]:
ped_data = ped_data.dropna()

In [94]:
ped_data.head()

,Unnamed: 0,vehicleCount_sum,assetUid,latitude,longitude,time
1,0.0,462.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 09:00:00 2020
2,1.0,179.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 08:00:00 2020
3,2.0,63.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 07:00:00 2020
4,3.0,44.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 06:00:00 2020
5,4.0,49.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 05:00:00 2020

In [95]:
#######################
#######################

In [96]:
# PORTLAND DATA

portland_data = pd.read_csv('Final_merged_city_portland.csv')

In [97]:
portland_data

,Unnamed: 0,geo_id,centroid,year,geometry,total_tran,pop,edut,collegemale,collegefemale,households,income,zipcode,Empratio,estabratio,ratio_65,ratio_22_50,bus_ratio,bus_ratio_total,public_ratio,car_ratio,bicy_ratio,walked_ratio
0,2432,41051010402,POINT (-122.3356996936241 45.48566422279789),2010,MULTIPOLYGON (((-122.3868792758254 45.51902980...,2601.0,5717.0,3699.0,294.0,356.0,162.0,1859.0,97009,0.000000,0.000000,0.391464,0.091307,0.490196,0.009612,0.019608,0.891580,0.005767,0.014994
1,2435,41051010402,POINT (-122.3356996936241 45.48566422279789),2011,MULTIPOLYGON (((-122.3868792758254 45.51902980...,2826.0,6037.0,4024.0,368.0,476.0,149.0,1960.0,97009,0.000000,0.000000,0.405831,0.108001,0.305970,0.014508,0.047417,0.866596,0.030432,0.009908
2,2438,41051010402,POINT (-122.3356996936241 45.48566422279789),2012,MULTIPOLYGON (((-122.3868792758254 45.51902980...,2868.0,6153.0,4090.0,369.0,507.0,139.0,1998.0,97009,0.000000,0.000000,0.393954,0.109052,0.266667,0.011158,0.041841,0.857043,0.033473,0.004533
3,2441,41051010402,POINT (-122.3356996936241 45.48566422279789),2013,MULTIPOLYGON (((-122.3868792758254 45.51902980...,2876.0,6022.0,3931.0,296.0,404.0,129.0,2087.0,97009,0.000000,0.000000,0.366490,0.108602,0.321739,0.012865,0.039986,0.858832,0.025730,0.012517
4,2444,41051010402,POINT (-122.335683996136 45.48565935229686),2014,MULTIPOLYGON (((-122.3868792758254 45.51902980...,3078.0,6181.0,4094.0,316.0,457.0,120.0,2191.0,97009,0.000000,0.000000,0.387316,0.108720,0.264368,0.007472,0.028265,0.875569,0.016244,0.023392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2603,1967,41051009000,POINT (-122.5306977041103 45.49261599741428),2013,MULTIPOLYGON (((-122.5377964271651 45.48742414...,3615.0,8815.0,5598.0,250.0,333.0,155.0,2979.0,97266,8.853565,0.551060,0.378900,0.112082,0.931354,0.138866,0.149101,0.751591,0.000000,0.037344
2604,1969,41051009000,POINT (-122.5306977041103 45.49261599741428),2014,MULTIPOLYGON (((-122.5377964271651 45.48742414...,4006.0,9787.0,6067.0,372.0,404.0,157.0,3105.0,97266,9.739884,0.569364,0.398079,0.100848,0.954183,0.119571,0.125312,0.763105,0.000000,0.028208
2605,1971,41051009000,POINT (-122.5306977041103 45.49261599741428),2015,MULTIPOLYGON (((-122.5377964271651 45.48742414...,4525.0,10489.0,6588.0,468.0,340.0,165.0,3248.0,97266,9.739884,0.573218,0.427019,0.094289,0.970642,0.116906,0.120442,0.784530,0.000000,0.013481
2606,1973,41051009000,POINT (-122.5306977041103 45.49261599741428),2016,MULTIPOLYGON (((-122.5377964271651 45.48742414...,4617.0,10809.0,6682.0,422.0,356.0,156.0,3173.0,97266,9.759152,0.589595,0.418818,0.097419,0.956153,0.146415,0.153130,0.750054,0.003465,0.019493
2607,1975,41051009000,POINT (-122.5306977041103 45.49261599741428),2017,MULTIPOLYGON (((-122.5377964271651 45.48742414...,4816.0,11030.0,6790.0,521.0,261.0,153.0,3241.0,97266,7.822736,0.570328,0.436265,0.094198,0.956693,0.151370,0.158223,0.746885,0.003530,0.019103

In [98]:
temp = portland_data.loc[portland_data['year'] == 2013]

In [99]:
pGeo = temp[['geo_id', 'geometry']]

In [100]:
pGeo = pGeo.drop_duplicates(keep='first')

In [101]:
pGeo

           geo_id                                           geometry
3     41051010402  MULTIPOLYGON (((-122.3868792758254 45.51902980...
11    41051010500  MULTIPOLYGON (((-122.3970989671113 45.57260058...
27    41051009603  MULTIPOLYGON (((-122.4661255423961 45.53952849...
35    41051010100  MULTIPOLYGON (((-122.4566475168594 45.53948853...
43    41051010200  MULTIPOLYGON (((-122.5865501307936 45.59923808...
...           ...                                                ...
2451  41051006100  MULTIPOLYGON (((-122.7103377578295 45.49058056...
2491  41051000601  MULTIPOLYGON (((-122.5787875151165 45.49027201...
2499  41051000602  MULTIPOLYGON (((-122.5790644457624 45.47586897...
2555  41051008302  MULTIPOLYGON (((-122.5657575052936 45.49323006...
2595  41051008902  MULTIPOLYGON (((-122.5790413899689 45.46437394...

[171 rows x 2 columns]

In [102]:
##########################
##########################

In [104]:
# CONVERTING THE COLUMNS TO BE COMPATIBLE WITH PLOTTING

pGeo['geometry'] = pGeo['geometry'].apply(wkt.loads)
pGeo = gpd.GeoDataFrame(pGeo, geometry='geometry')

In [105]:
pGeo

           geo_id                                           geometry
3     41051010402  MULTIPOLYGON (((-122.38688 45.51903, -122.3726...
11    41051010500  MULTIPOLYGON (((-122.39710 45.57260, -122.3918...
27    41051009603  MULTIPOLYGON (((-122.46613 45.53953, -122.4656...
35    41051010100  MULTIPOLYGON (((-122.45665 45.53949, -122.4533...
43    41051010200  MULTIPOLYGON (((-122.58655 45.59924, -122.5860...
...           ...                                                ...
2451  41051006100  MULTIPOLYGON (((-122.71034 45.49058, -122.7025...
2491  41051000601  MULTIPOLYGON (((-122.57879 45.49027, -122.5749...
2499  41051000602  MULTIPOLYGON (((-122.57906 45.47587, -122.5790...
2555  41051008302  MULTIPOLYGON (((-122.56576 45.49323, -122.5657...
2595  41051008902  MULTIPOLYGON (((-122.57904 45.46437, -122.5686...

[171 rows x 2 columns]

In [106]:
portland_data_gdf = gpd.GeoDataFrame(pGeo, geometry='geometry', crs={'init': 'epsg:4326'})

In [107]:
portland_data_gdf.shape

(171, 2)

In [108]:
portland_data_gdf.head()

         geo_id                                           geometry
3   41051010402  MULTIPOLYGON (((-122.38688 45.51903, -122.3726...
11  41051010500  MULTIPOLYGON (((-122.39710 45.57260, -122.3918...
27  41051009603  MULTIPOLYGON (((-122.46613 45.53953, -122.4656...
35  41051010100  MULTIPOLYGON (((-122.45665 45.53949, -122.4533...
43  41051010200  MULTIPOLYGON (((-122.58655 45.59924, -122.5860...

In [109]:
ped_data_gdf = gpd.GeoDataFrame(ped_data, geometry=gpd.points_from_xy(ped_data.longitude, ped_data.latitude))

In [110]:
ped_data_gdf = gpd.GeoDataFrame(ped_data_gdf, geometry='geometry', crs={'init': 'epsg:4326'})

In [111]:
ped_data_gdf

,Unnamed: 0,vehicleCount_sum,assetUid,latitude,longitude,time,geometry
1,0.0,462.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 09:00:00 2020,POINT (-122.60016 45.50530)
2,1.0,179.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 08:00:00 2020,POINT (-122.60016 45.50530)
3,2.0,63.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 07:00:00 2020,POINT (-122.60016 45.50530)
4,3.0,44.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 06:00:00 2020,POINT (-122.60016 45.50530)
5,4.0,49.0,01ec53e2-8464-4d0b-b0d4-76e1904d9af7,45.505296,-122.600155,Fri Jan 31 05:00:00 2020,POINT (-122.60016 45.50530)
...,...,...,...,...,...,...,...
18476,18475.0,613.0,f8e18220-9969-49f4-b282-8ee190029754,45.504743,-122.634463,Fri Jan 24 14:00:00 2020,POINT (-122.63446 45.50474)
18477,18476.0,565.0,f8e18220-9969-49f4-b282-8ee190029754,45.504743,-122.634463,Fri Jan 24 13:00:00 2020,POINT (-122.63446 45.50474)
18478,18477.0,640.0,f8e18220-9969-49f4-b282-8ee190029754,45.504743,-122.634463,Fri Jan 24 12:00:00 2020,POINT (-122.63446 45.50474)
18479,18478.0,673.0,f8e18220-9969-49f4-b282-8ee190029754,45.504743,-122.634463,Fri Jan 24 11:00:00 2020,POINT (-122.63446 45.50474)
18480,18479.0,507.0,f8e18220-9969-49f4-b282-8ee190029754,45.504743,-122.634463,Fri Jan 24 10:00:00 2020,POINT (-122.63446 45.50474)

In [112]:
ped_data_gdf.shape

(18480, 7)

In [114]:
# SPATIAL JOIN WITH PEDESTRIAN AND PORTLAND

sjoined_listings = gpd.sjoin(ped_data_gdf, portland_data_gdf, op='within',how='right')
sjoined_listings = sjoined_listings[['geo_id', 'vehicleCount_sum']]
sjoined_listings = sjoined_listings.dropna()
sjoined_listings

                  geo_id  vehicleCount_sum
index_right
499          41051000801              96.0
499          41051000801             735.0
499          41051000801             836.0
499          41051000801             836.0
499          41051000801             940.0
...                  ...               ...
2339         41051009000            1027.0
2339         41051009000             985.0
2339         41051009000            1012.0
2339         41051009000             969.0
2339         41051009000             975.0

[18480 rows x 2 columns]

In [116]:
df = sjoined_listings.groupby('geo_id')['vehicleCount_sum'].mean()

In [117]:
df

geo_id
41051000701     678.899725
41051000801     543.757738
41051000901     435.173280
41051001000     398.035714
41051001101     715.220238
41051001102     717.517857
41051001201     715.497024
41051001202     738.537415
41051001301     666.334524
41051001302     692.154762
41051001400     484.739087
41051001601     745.059524
41051001602     898.804894
41051008201    1080.082589
41051008202    1037.550265
41051009000     722.251190
41051009201     753.144841
Name: vehicleCount_sum, dtype: float64

In [118]:
df.mean()

707.2212158046977

In [119]:
pGeo = pGeo.set_index('geo_id')

In [120]:
result['vehicleCountSum'] = df

In [81]:
df1 = pd.merge(pGeo, df, left_index=True, right_index=True, how='left')

In [121]:
result = result.fillna(707.22)

In [90]:
result = pGeo.copy()

In [124]:
for i, c in result.iterrows():
    print(c)

geometry              (POLYGON ((-122.3868792758254 45.5190298016209...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010402, dtype: object
geometry              (POLYGON ((-122.3970989671113 45.5726005840231...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010500, dtype: object
geometry              (POLYGON ((-122.4661255423961 45.5395284963269...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009603, dtype: object
geometry              (POLYGON ((-122.4566475168594 45.5394885343066...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010100, dtype: object
geometry              (POLYGON ((-122.5865501307936 45.5992380830268...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010200, dtype: object
geometry              (POLYGON ((-122.4336984445508 45.5366666241537...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010304, dtype: object
geometry              (POLYGON ((-122.475774467029 45.51914743867257...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009801, dtype: object
geometry              (POLYGON ((-122.4847343307979 45.4864913321540...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009803, dtype: object
geometry              (POLYGON ((-122.4676063127464 45.4887004091136...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009904, dtype: object
geometry              (POLYGON ((-122.4483452516475 45.4809574528875...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009906, dtype: object
geometry              (POLYGON ((-122.4546922182964 45.4701013823865...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009907, dtype: object
geometry              (POLYGON ((-122.4448413736532 45.5126735596893...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010001, dtype: object
geometry              (POLYGON ((-122.4647893250282 45.4928564373434...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010002, dtype: object
geometry              (POLYGON ((-122.433619410099 45.52782261758035...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010303, dtype: object
geometry              (POLYGON ((-122.4337833766111 45.5190836101013...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010405, dtype: object
geometry              (POLYGON ((-122.399963282562 45.51192374350313...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010407, dtype: object
geometry              (POLYGON ((-122.4138962754812 45.5016916789942...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010408, dtype: object
geometry              (POLYGON ((-122.414723309194 45.51124368236234...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010410, dtype: object
geometry              (POLYGON ((-122.413891286087 45.50484968125275...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010411, dtype: object
geometry              (POLYGON ((-122.6965005474965 45.4585545603319...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006300, dtype: object
geometry              (POLYGON ((-122.7113274256682 45.4338984752218...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006402, dtype: object
geometry              (POLYGON ((-122.7439684744601 45.4344693822779...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006404, dtype: object
geometry              (POLYGON ((-122.9291148864933 45.6426462694611...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007100, dtype: object
geometry              (POLYGON ((-122.3911553410771 45.5392617968477...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010305, dtype: object
geometry              (POLYGON ((-122.3992933457855 45.5335597604576...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010306, dtype: object
geometry              (POLYGON ((-122.5493773955564 45.4760400721489...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008901, dtype: object
geometry              (POLYGON ((-122.4943642936196 45.4740152479280...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009903, dtype: object
geometry              (POLYGON ((-122.4754713193627 45.4872643719887...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009905, dtype: object
geometry              (POLYGON ((-122.4016272228507 45.4927476930452...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010409, dtype: object
geometry              (POLYGON ((-122.7193498712782 45.5073435527340...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004602, dtype: object
geometry              (POLYGON ((-122.6982039085651 45.5212936303858...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005200, dtype: object
geometry              (POLYGON ((-122.6936248679184 45.5155556455087...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005500, dtype: object
geometry              (POLYGON ((-122.6881158444333 45.5132216645698...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005600, dtype: object
geometry              (POLYGON ((-122.6820157877157 45.5051196840284...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005700, dtype: object
geometry              (POLYGON ((-122.7132148308416 45.5021755736373...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005800, dtype: object
geometry              (POLYGON ((-122.6827526961412 45.4886206588967...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005900, dtype: object
geometry              (POLYGON ((-122.6972327638904 45.4957856220652...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006001, dtype: object
geometry              (POLYGON ((-122.6848688715688 45.5192096777058...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051010600, dtype: object
geometry              (POLYGON ((-122.6685096758439 45.4896287092521...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000100, dtype: object
geometry              (POLYGON ((-122.6511506479096 45.4903237698433...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000200, dtype: object
geometry              (POLYGON ((-122.6435166338574 45.4903107958509...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000301, dtype: object
geometry              (POLYGON ((-122.6376585383979 45.4743597792970...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000302, dtype: object
geometry              (POLYGON ((-122.6205705527944 45.4827708556041...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000401, dtype: object
geometry              (POLYGON ((-122.6226536727048 45.5047958930627...
pedestrianCountSum                                              16.1806
vehicleCountSum                                                 543.758
Name: 41051000801, dtype: object
geometry              (POLYGON ((-122.6226356112724 45.493325874405,...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22

Name: 41051000802, dtype: object
geometry              (POLYGON ((-122.6396466892322 45.5019458319198...
pedestrianCountSum                                              18.5179
vehicleCountSum                                                 435.173
Name: 41051000901, dtype: object
geometry              (POLYGON ((-122.6396166673302 45.4979348264700...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000902, dtype: object
geometry              (POLYGON ((-122.6618667480103 45.5048897549546...
pedestrianCountSum                                              15.5536
vehicleCountSum                                                 398.036
Name: 41051001000, dtype: object
geometry              (POLYGON ((-122.6686518316401 45.5175867352497...
pedestrianCountSum                                                   22
vehicleCountSum                                                  715.22
Name: 41051001101, dtype: object
geometry              (POLYGON ((-122.6628047907098 45.5122367542549...
pedestrianCountSum                                              34.3929
vehicleCountSum                                                 717.518
Name: 41051001102, dtype: object
geometry              (POLYGON ((-122.6499297460283 45.5086207985298...
pedestrianCountSum                                              11.9494
vehicleCountSum                                                 738.537
Name: 41051001202, dtype: object
geometry              (POLYGON ((-122.6347707363134 45.512063853782,...
pedestrianCountSum                                              27.0878
vehicleCountSum                                                 692.155
Name: 41051001302, dtype: object
geometry              (POLYGON ((-122.6230057541571 45.5192878993068...
pedestrianCountSum                                                   33
vehicleCountSum                                                 484.739
Name: 41051001400, dtype: object
geometry              (POLYGON ((-122.7166753471116 45.5938355739066...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003901, dtype: object
geometry              (POLYGON ((-122.7145722605402 45.5789835799369...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003902, dtype: object
geometry              (POLYGON ((-122.7358843418226 45.5863374988501...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004001, dtype: object
geometry              (POLYGON ((-122.7408313281255 45.5821854796273...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004002, dtype: object
geometry              (POLYGON ((-122.7801415839191 45.6194964054551...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004101, dtype: object
geometry              (POLYGON ((-122.7510403842378 45.5889914426636...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004102, dtype: object
geometry              (POLYGON ((-122.7771594584098 45.5979694013166...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004200, dtype: object
geometry              (POLYGON ((-122.7911296320992 45.6258963948417...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007202, dtype: object
geometry              (POLYGON ((-122.7208909469945 45.5204335488388...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004601, dtype: object
geometry              (POLYGON ((-122.6089925705297 45.4902919135461...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000402, dtype: object
geometry              (POLYGON ((-122.5995885064194 45.4809369207767...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000501, dtype: object
geometry              (POLYGON ((-122.5963935475611 45.4903129565691...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000502, dtype: object
geometry              (POLYGON ((-122.5994416317342 45.5053869751971...
pedestrianCountSum                                                   22
vehicleCountSum                                                   678.9
Name: 41051000701, dtype: object
geometry              (POLYGON ((-122.6018395934989 45.4974629568263...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000702, dtype: object
geometry              (POLYGON ((-122.612564719018 45.5165529351758,...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051001500, dtype: object
geometry              (POLYGON ((-122.6019927000291 45.5167599730495...
pedestrianCountSum                                                   22
vehicleCountSum                                                  745.06
Name: 41051001601, dtype: object
geometry              (POLYGON ((-122.589348427813 45.46864692094037...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008600, dtype: object
geometry              (POLYGON ((-122.6160355031208 45.4746728505174...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008700, dtype: object
geometry              (POLYGON ((-122.6158954532035 45.4650088268242...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008800, dtype: object
geometry              (POLYGON ((-122.6859319649592 45.5356276781762...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005100, dtype: object
geometry              (POLYGON ((-122.7244170641965 45.5403075382606...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004500, dtype: object
geometry              (POLYGON ((-122.6986339605812 45.5304966307645...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004800, dtype: object
geometry              (POLYGON ((-122.7008519923495 45.5354486237087...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004900, dtype: object
geometry              (POLYGON ((-122.6947609814063 45.5355646459518...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051005000, dtype: object
geometry              (POLYGON ((-122.833371556315 45.60564032080291...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004300, dtype: object
geometry              (POLYGON ((-122.712490003264 45.53342958095102...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051004700, dtype: object
geometry              (POLYGON ((-122.7438579697715 45.5166594663745...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006900, dtype: object
geometry              (POLYGON ((-122.8673785929985 45.6062682713782...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007000, dtype: object
geometry              (POLYGON ((-122.6306839402941 45.5500628867383...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003000, dtype: object
geometry              (POLYGON ((-122.6406459620566 45.5505708500357...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003100, dtype: object
geometry              (POLYGON ((-122.6503569946369 45.5531068150451...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003200, dtype: object
geometry              (POLYGON ((-122.6615010492829 45.5591177757603...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003301, dtype: object
geometry              (POLYGON ((-122.6615360239735 45.5545607739899...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003302, dtype: object
geometry              (POLYGON ((-122.6754460555651 45.5554887224532...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003401, dtype: object
geometry              (POLYGON ((-122.6755110508346 45.5546167219467...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003402, dtype: object
geometry              (POLYGON ((-122.6614030896692 45.5664037787522...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003601, dtype: object
geometry              (POLYGON ((-122.6517591376527 45.5783048198974...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003602, dtype: object
geometry              (POLYGON ((-122.6306520415236 45.5682378956781...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003603, dtype: object
geometry              (POLYGON ((-122.674805167427 45.57580273105533...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003701, dtype: object
geometry              (POLYGON ((-122.6748691347891 45.5699177290133...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22

Name: 41051003702, dtype: object
geometry              (POLYGON ((-122.6463651618068 45.5844768431134...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007300, dtype: object
geometry              (POLYGON ((-122.677929985887 45.54212270927307...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002203, dtype: object
geometry              (POLYGON ((-122.679321982328 45.54100770383748...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002303, dtype: object
geometry              (POLYGON ((-122.658588983296 45.54826178262662...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002401, dtype: object
geometry              (POLYGON ((-122.6575609297833 45.5390037829496...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002402, dtype: object
geometry              (POLYGON ((-122.6473139273557 45.5420668217528...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002501, dtype: object
geometry              (POLYGON ((-122.6473339101248 45.5389668203851...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002502, dtype: object
geometry              (POLYGON ((-122.6306919302053 45.5482498858290...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002600, dtype: object
geometry              (POLYGON ((-122.6229648727033 45.5405689104476...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002701, dtype: object
geometry              (POLYGON ((-122.6229658641433 45.5390329096504...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002702, dtype: object
geometry              (POLYGON ((-122.5964807536804 45.5282609999158...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051001701, dtype: object
geometry              (POLYGON ((-122.6172987830355 45.5264179235958...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051001801, dtype: object
geometry              (POLYGON ((-122.6316738106159 45.5264558717090...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051001900, dtype: object
geometry              (POLYGON ((-122.6106758669184 45.5437229573147...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002801, dtype: object
geometry              (POLYGON ((-122.61092381942 45.53511995153625,...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002802, dtype: object
geometry              (POLYGON ((-122.6045098883381 45.5496659835290...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002901, dtype: object
geometry              (POLYGON ((-122.6002347795671 45.5316209883791...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002902, dtype: object
geometry              (POLYGON ((-122.6204229917858 45.5627979314859...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007500, dtype: object
geometry              (POLYGON ((-122.6495997811882 45.5150458023207...
pedestrianCountSum                                              18.4747
vehicleCountSum                                                 715.497
Name: 41051001201, dtype: object
geometry              (POLYGON ((-122.634824776772 45.51930585698213...
pedestrianCountSum                                                32.68
vehicleCountSum                                                 666.335
Name: 41051001301, dtype: object
geometry              (POLYGON ((-122.6454908209558 45.5235898205986...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002000, dtype: object
geometry              (POLYGON ((-122.6690018881706 45.5276207373036...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002100, dtype: object
geometry              (POLYGON ((-122.6178007441805 45.5192769179442...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051001802, dtype: object
geometry              (POLYGON ((-122.5790446695041 45.5191250566527...
pedestrianCountSum                                                   22
vehicleCountSum                                                 898.805
Name: 41051001602, dtype: object
geometry              (POLYGON ((-122.579054689898 45.52277605915498...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051001702, dtype: object
geometry              (POLYGON ((-122.568607709552 45.52986110194845...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008100, dtype: object
geometry              (POLYGON ((-122.5668256661286 45.5226901030661...
pedestrianCountSum                                                   22
vehicleCountSum                                                 1080.08
Name: 41051008201, dtype: object
geometry              (POLYGON ((-122.5582886495688 45.5226361337198...
pedestrianCountSum                                                   22
vehicleCountSum                                                 1037.55
Name: 41051008202, dtype: object
geometry              (POLYGON ((-122.5787005495399 45.4974060371655...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008301, dtype: object
geometry              (POLYGON ((-122.6975561376493 45.5626936415414...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003501, dtype: object
geometry              (POLYGON ((-122.6942240940351 45.555991652544,...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003502, dtype: object
geometry              (POLYGON ((-122.6924632414798 45.5830926654554...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003801, dtype: object
geometry              (POLYGON ((-122.6924202081422 45.5771156642211...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003802, dtype: object
geometry              (POLYGON ((-122.6945321721557 45.5699276545383...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051003803, dtype: object
geometry              (POLYGON ((-122.7637747633592 45.6544184332048...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007201, dtype: object
geometry              (POLYGON ((-122.7232292339641 45.5712505459859...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051980000, dtype: object
geometry              (POLYGON ((-122.620409024008 45.56858293458725...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007400, dtype: object
geometry              (POLYGON ((-122.5985249245811 45.5582030109641...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007600, dtype: object
geometry              (POLYGON ((-122.6982736618718 45.4778265877647...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006002, dtype: object
geometry              (POLYGON ((-122.7101285619123 45.4573415160671...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006200, dtype: object
geometry              (POLYGON ((-122.7311945339708 45.4472474368127...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006403, dtype: object
geometry              (POLYGON ((-122.7436115993061 45.4548624092965...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006501, dtype: object
geometry              (POLYGON ((-122.7245256072254 45.4611244770304...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006502, dtype: object
geometry              (POLYGON ((-122.7436616891203 45.4694614277434...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006601, dtype: object
geometry              (POLYGON ((-122.7231386954153 45.4762305035911...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006602, dtype: object
geometry              (POLYGON ((-122.7437097797722 45.4841954463549...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006701, dtype: object
geometry              (POLYGON ((-122.7271377460249 45.4834985009037...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006702, dtype: object
geometry              (POLYGON ((-122.5790167527082 45.5340440671265...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051002903, dtype: object
geometry              (POLYGON ((-122.5786148712362 45.5554200834888...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007700, dtype: object
geometry              (POLYGON ((-122.5737218564602 45.5544381010295...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007800, dtype: object
geometry              (POLYGON ((-122.5577497907325 45.5481011555666...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051007900, dtype: object
geometry              (POLYGON ((-122.5633177225628 45.5339951242619...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008001, dtype: object
geometry              (POLYGON ((-122.5490197223492 45.5388281802796...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008002, dtype: object
geometry              (POLYGON ((-122.5381998047301 45.5572582357684...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009502, dtype: object
geometry              (POLYGON ((-122.7437898297179 45.4922964563981...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006801, dtype: object
geometry              (POLYGON ((-122.7303637805083 45.4882564967807...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006802, dtype: object
geometry              (POLYGON ((-122.5106515569565 45.5222983046652...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009301, dtype: object
geometry              (POLYGON ((-122.5377476308519 45.5262882107253...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009302, dtype: object
geometry              (POLYGON ((-122.5375637043858 45.5395132228147...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009400, dtype: object
geometry              (POLYGON ((-122.5373407516222 45.5480442310095...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009501, dtype: object
geometry              (POLYGON ((-122.4773105889405 45.5428494545730...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009604, dtype: object
geometry              (POLYGON ((-122.496305556221 45.52735336306446...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009605, dtype: object
geometry              (POLYGON ((-122.4964545282071 45.5221963572827...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009606, dtype: object
geometry              (POLYGON ((-122.5377656096624 45.5224892073815...
pedestrianCountSum                                              17.5179
vehicleCountSum                                                 753.145
Name: 41051009201, dtype: object
geometry              (POLYGON ((-122.5210195588172 45.5190982644225...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009202, dtype: object
geometry              (POLYGON ((-122.5107274895271 45.5102112926310...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009701, dtype: object
geometry              (POLYGON ((-122.4965994448724 45.5069973414247...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009702, dtype: object
geometry              (POLYGON ((-122.4968643987281 45.4980853263157...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009804, dtype: object
geometry              (POLYGON ((-122.548007526976 45.5041921555338,...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008400, dtype: object
geometry              (POLYGON ((-122.5574044200961 45.4783350528930...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008500, dtype: object
geometry              (POLYGON ((-122.5377964271651 45.4874241470326...
pedestrianCountSum                                              16.9405
vehicleCountSum                                                 722.251
Name: 41051009000, dtype: object
geometry              (POLYGON ((-122.5237254799621 45.5040662409002...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009101, dtype: object
geometry              (POLYGON ((-122.5235684070879 45.4887061995017...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051009102, dtype: object
geometry              (POLYGON ((-122.7103377578295 45.4905805683884...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051006100, dtype: object

geometry              (POLYGON ((-122.5787875151165 45.4902720164976...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000601, dtype: object
geometry              (POLYGON ((-122.5790644457624 45.4758689744753...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051000602, dtype: object
geometry              (POLYGON ((-122.5657575052936 45.4932300697451...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008302, dtype: object
geometry              (POLYGON ((-122.5790413899689 45.4643739417641...
pedestrianCountSum                                                   22
vehicleCountSum                                                  707.22
Name: 41051008902, dtype: object

In [125]:
result.to_csv('CityIQ_pedveh_Count.csv')

In [ ]:
######################
######################

In [ ]:
veh_data = pd.read_csv('C:/Users/Ram/Desktop/Portland_CARTO_notebook-jason-cityIQ/vehicle_count_sample.csv')
veh_data = veh_data.dropna()

In [ ]:
veh_data

In [ ]:
veh_data_gdf = gpd.GeoDataFrame(veh_data, geometry=gpd.points_from_xy(veh_data.longitude, veh_data.latitude))

In [ ]:
veh_data_gdf = gpd.GeoDataFrame(veh_data_gdf, geometry='geometry', crs={'init': 'epsg:4326'})

In [ ]:
######################
######################

In [ ]:
# SPATIAL JOIN WITH PEDESTRIAN AND PORTLAND

sjoined_listings_veh = gpd.sjoin(veh_data_gdf, portland_data_gdf, op='within',how='inner')
sjoined_listings_veh.head()

In [ ]:
sjoined_listings_veh.shape
# veh_data_gdf.shape
# portland_data_gdf.shape

In [ ]:
sjoined_listings_veh['geometry'] = sjoined_listings_veh['geometry'].apply(wkt.loads)
sjoined_listings_veh['centroid'] = sjoined_listings_veh['centroid'].apply(wkt.loads)
sjoined_listings_veh = gpd.GeoDataFrame(sjoined_listings_veh, geometry='geometry')

In [ ]:
sjoined_listings_veh_gdf = gpd.GeoDataFrame(sjoined_listings_veh, geometry='geometry', crs={'init': 'epsg:4326'})

In [ ]:
sjoined_listings_gdf = gpd.GeoDataFrame(sjoined_listings, geometry='geometry', crs={'init': 'epsg:4326'})

In [ ]:
Map([Layer(portland_data_gdf),Layer(sjoined_listings_veh_gdf)])