In [2]:
from autocensus import Query
import pandas as pd

In [3]:
# Configure query for total population 
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B00001_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfp = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [3]:
# Configure query for No. of Households
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B00002_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfh = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [4]:
# Configure query for No. of Household Income
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B19001_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfhi = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [5]:
# Configure query for No. of Households Age
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B19037_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfa = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [6]:
# Configure query for No. of GINI
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B19083_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfg = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [7]:
dfh.head()

,name,geo_id,geo_type,year,date,variable_code,variable_label,variable_concept,annotation,value,percent_change,difference,centroid,internal_point,geometry
0,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,225.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
1,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2015,2015-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,222.0,-0.013333,-3.0,POINT (-73.36014879909517 41.52086129452177),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
2,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2016,2016-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,224.0,0.009009,2.0,POINT (-73.36014879909517 41.52086129452177),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
3,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2017,2017-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,220.0,-0.017857,-4.0,POINT (-73.36014872509649 41.52086117449242),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
4,"Census Tract 2531, Litchfield County, Connecticut",1400000US09005253100,tract,2014,2014-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,128.0,NaN,NaN,POINT (-73.4084633860346 41.59733466354592),POINT (-73.4087229757659 41.602294),"(POLYGON ((-73.423655 41.587736, -73.421336999..."

In [8]:
dfp.columns

Index(['name', 'geo_id', 'geo_type', 'year', 'date', 'variable_code',
       'variable_label', 'variable_concept', 'annotation', 'value',
       'percent_change', 'difference', 'centroid', 'internal_point',
       'geometry'],
      dtype='object')

In [9]:
dfh.columns

Index(['name', 'geo_id', 'geo_type', 'year', 'date', 'variable_code',
       'variable_label', 'variable_concept', 'annotation', 'value',
       'percent_change', 'difference', 'centroid', 'internal_point',
       'geometry'],
      dtype='object')

In [10]:
dfp.rename(columns={'value':'pop'}, 
                 inplace=True)

In [11]:
dfh.rename(columns={'value':'households'}, 
                 inplace=True)

In [12]:
dfhi.rename(columns={'value':'income'}, 
                 inplace=True)

In [13]:
dfa.rename(columns={'value':'age'}, 
                 inplace=True)

In [14]:
dfg.rename(columns={'value':'gini'}, 
                 inplace=True)

In [15]:
dfm = pd.merge(dfp, dfh[['households','geo_id']],how='outer', on='geo_id')

In [16]:
dfm = pd.merge(dfm, dfhi[['income','geo_id']], on='geo_id')

In [17]:
dfm = pd.merge(dfm, dfg[['gini','geo_id']], on='geo_id')

In [18]:
dfm.head()

,name,geo_id,geo_type,year,date,variable_code,variable_label,variable_concept,annotation,pop,percent_change,difference,centroid,internal_point,geometry,households,income,gini
0,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4918
1,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4913
2,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4613
3,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4560
4,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,753.0,0.4918

In [19]:
dfm.columns

Index(['name', 'geo_id', 'geo_type', 'year', 'date', 'variable_code',
       'variable_label', 'variable_concept', 'annotation', 'pop',
       'percent_change', 'difference', 'centroid', 'internal_point',
       'geometry', 'households', 'income', 'gini'],
      dtype='object')

In [20]:
from linearmodels.panel import PanelOLS
from linearmodels import RandomEffects

In [21]:
year = pd.to_datetime(dfm['year'], format='%Y')

In [22]:
year = pd.Categorical(year)

In [23]:
print(year)

[2014-01-01, 2014-01-01, 2014-01-01, 2014-01-01, 2014-01-01, ..., 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-01]
Length: 13056
Categories (4, datetime64[ns]): [2014-01-01, 2015-01-01, 2016-01-01, 2017-01-01]

In [24]:
dfm = dfm.set_index(['pop', 'year'])

In [25]:
dfm.head()

                                                         name  \
pop   year
446.0 2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut

                          geo_id geo_type       date variable_code  \
pop   year
446.0 2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E

           variable_label                           variable_concept  \
pop   year
446.0 2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population

           annotation  percent_change  difference  \
pop   year
446.0 2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN

                                                centroid  \
pop   year
446.0 2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)

                                   internal_point  \
pop   year
446.0 2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)

                                                     geometry  households  \
pop   year
446.0 2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0

            income    gini
pop   year
446.0 2014   765.0  0.4918
      2014   765.0  0.4913
      2014   765.0  0.4613
      2014   765.0  0.4560
      2014   753.0  0.4918

In [26]:
dfm['year'] = year

In [27]:
dfm.head()

                                                         name  \
pop   year
446.0 2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut

                          geo_id geo_type       date variable_code  \
pop   year
446.0 2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E

           variable_label                           variable_concept  \
pop   year
446.0 2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population

           annotation  percent_change  difference  \
pop   year
446.0 2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN

                                                centroid  \
pop   year
446.0 2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)

                                   internal_point  \
pop   year
446.0 2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)

                                                     geometry  households  \
pop   year
446.0 2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0

            income    gini       year
pop   year
446.0 2014   765.0  0.4918 2014-01-01
      2014   765.0  0.4913 2014-01-01
      2014   765.0  0.4613 2014-01-01
      2014   765.0  0.4560 2014-01-01
      2014   753.0  0.4918 2014-01-01

In [28]:

from linearmodels.panel import PooledOLS
import statsmodels.api as sm

In [29]:
exog_vars = ['households','income', 'year']
exog = sm.add_constant(dfm[exog_vars])

/home/pak348/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [30]:
mod = PooledOLS(dfm.gini, exog)
pooled_res = mod.fit()
print(pooled_res)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                   gini   R-squared:                        0.1591
Estimator:                  PooledOLS   R-squared (Between):              0.1806
No. Observations:               13056   R-squared (Within):               0.1065
Date:                Mon, Oct 28 2019   R-squared (Overall):              0.1591
Time:                        16:41:34   Log-likelihood                  1.89e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      493.74
Entities:                         154   P-value                           0.0000
Avg Obs:                       84.779   Distribution:                 F(5,13050)
Min Obs:                       64.000
Max Obs:                       256.00   F-statistic (robust):             493.74
                                        P-value                           0.0000
Time periods:                       4   Distribution:                 F(5,13050)
Avg Obs:                       3264.0
Min Obs:                       3264.0
Max Obs:                       3264.0

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
const                        0.3981     0.0023     169.48     0.0000      0.3935      0.4027
households                   0.0004  1.031e-05     37.300     0.0000      0.0004      0.0004
income                   -2.616e-05   8.82e-07    -29.663     0.0000  -2.789e-05  -2.443e-05
year.2015-01-01 00:00:00  3.429e-17     0.0014  2.434e-14     1.0000     -0.0028      0.0028
year.2016-01-01 00:00:00  3.366e-17     0.0014  2.389e-14     1.0000     -0.0028      0.0028
year.2017-01-01 00:00:00  3.672e-17     0.0014  2.606e-14     1.0000     -0.0028      0.0028
============================================================================================

In [31]:
from linearmodels.panel import RandomEffects
mod = RandomEffects(dfm.gini, exog)
re_res = mod.fit()
print(re_res)

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                   gini   R-squared:                        0.2762
Estimator:              RandomEffects   R-squared (Between):             -1.4826
No. Observations:               13056   R-squared (Within):               0.2757
Date:                Mon, Oct 28 2019   R-squared (Overall):             -0.7958
Time:                        16:41:34   Log-likelihood                 2.676e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      995.87
Entities:                         154   P-value                           0.0000
Avg Obs:                       84.779   Distribution:                 F(5,13050)
Min Obs:                       64.000
Max Obs:                       256.00   F-statistic (robust):             907.02
                                        P-value                           0.0000
Time periods:                       4   Distribution:                 F(5,13050)
Avg Obs:                       3264.0
Min Obs:                       3264.0
Max Obs:                       3264.0

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
const                        0.1790     0.0063     28.341     0.0000      0.1666      0.1914
households                   0.0016  2.681e-05     59.450     0.0000      0.0015      0.0016
income                    3.108e-06  1.064e-06     2.9226     0.0035   1.024e-06   5.193e-06
year.2015-01-01 00:00:00    -0.0287     0.0016    -17.558     0.0000     -0.0319     -0.0255
year.2016-01-01 00:00:00    -0.0097     0.0017    -5.6884     0.0000     -0.0131     -0.0064
year.2017-01-01 00:00:00    -0.0170     0.0015    -10.996     0.0000     -0.0200     -0.0139
============================================================================================

mod = PanelOLS(dfp.value, dfh.value, entity_effects=True)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

In [33]:
from linearmodels.panel import PanelOLS
exog_vars1 = ['households','income']
exog1 = sm.add_constant(dfm[exog_vars1])

In [34]:
mod = PanelOLS(dfm.gini, exog1, entity_effects=True, time_effects=True)
fe_te_res = mod.fit()
print(fe_te_res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                   gini   R-squared:                        0.2406
Estimator:                   PanelOLS   R-squared (Between):             -1.8887
No. Observations:               13056   R-squared (Within):               0.2570
Date:                Mon, Oct 28 2019   R-squared (Overall):             -1.0431
Time:                        16:45:42   Log-likelihood                   2.7e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      2043.5
Entities:                         154   P-value                           0.0000
Avg Obs:                       84.779   Distribution:                 F(2,12897)
Min Obs:                       64.000
Max Obs:                       256.00   F-statistic (robust):             2043.5
                                        P-value                           0.0000
Time periods:                       4   Distribution:                 F(2,12897)
Avg Obs:                       3264.0
Min Obs:                       3264.0
Max Obs:                       3264.0

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          0.1384     0.0050     27.645     0.0000      0.1286      0.1482
households     0.0018   2.82e-05     62.729     0.0000      0.0017      0.0018
income      5.554e-06  1.066e-06     5.2112     0.0000   3.465e-06   7.643e-06
==============================================================================

F-test for Poolability: 203.57
P-value: 0.0000
Distribution: F(156,12897)

Included effects: Entity, Time

In [37]:
from linearmodels.panel import compare
print(compare({'RE':re_res,'Pooled':fe_te_res}))

                       Model Comparison
=============================================================
                                     Pooled                RE
-------------------------------------------------------------
Dep. Variable                          gini              gini
Estimator                          PanelOLS     RandomEffects
No. Observations                      13056             13056
Cov. Est.                        Unadjusted        Unadjusted
R-squared                            0.2406            0.2762
R-Squared (Within)                   0.2570            0.2757
R-Squared (Between)                 -1.8887           -1.4826
R-Squared (Overall)                 -1.0431           -0.7958
F-statistic                          2043.5            995.87
P-value (F-stat)                     0.0000            0.0000
==========================     ============   ===============
const                                0.1384            0.1790
                                   (27.645)          (28.341)
households                           0.0018            0.0016
                                   (62.729)          (59.450)
income                            5.554e-06         3.108e-06
                                   (5.2112)          (2.9226)
year.2015-01-01 00:00:00                              -0.0287
                                                    (-17.558)
year.2016-01-01 00:00:00                              -0.0097
                                                    (-5.6884)
year.2017-01-01 00:00:00                              -0.0170
                                                    (-10.996)
============================ ============== =================
Effects                              Entity
                                       Time
-------------------------------------------------------------

T-stats reported in parentheses