In [134]:
from autocensus import Query
import pandas as pd

In [135]:
# Configure query for total population 
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B00001_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfp = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [136]:
# Configure query for No. of Households
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B00002_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfh = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [137]:
# Configure query for No. of Household Income
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B19001_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfhi = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [138]:
# Configure query for No. of Households Age
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B19037_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfa = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [139]:
# Configure query for No. of GINI
query = Query(
    estimate=5,
    years=[2014, 2015, 2016, 2017],
    variables=['B19083_001E'],
    for_geo='tract:*',
    in_geo=['state:09', 'county:005'],
    # Fill in the following with your actual Census API key
    census_api_key='0995bcf2c5a4aa42899cf705840809959c68cf75'
)

# Run query and collect output in dataframe
dfg = query.run()

Retrieving variables...
Retrieving ACS tables...
Retrieving shapefiles...
Merging ACS tables and variables...
Merging annotations...
Merging shapefiles...
Finalizing data...

In [145]:
dfh.head()

,name,geo_id,geo_type,year,date,variable_code,variable_label,variable_concept,annotation,value,percent_change,difference,centroid,internal_point,geometry
0,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,225.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
1,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2015,2015-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,222.0,-0.013333,-3.0,POINT (-73.36014879909517 41.52086129452177),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
2,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2016,2016-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,224.0,0.009009,2.0,POINT (-73.36014879909517 41.52086129452177),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
3,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2017,2017-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,220.0,-0.017857,-4.0,POINT (-73.36014872509649 41.52086117449242),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40..."
4,"Census Tract 2531, Litchfield County, Connecticut",1400000US09005253100,tract,2014,2014-12-31,B00002_001E,Total,Unweighted Sample Housing Units,NaN,128.0,NaN,NaN,POINT (-73.4084633860346 41.59733466354592),POINT (-73.4087229757659 41.602294),"(POLYGON ((-73.423655 41.587736, -73.421336999..."

In [146]:
dfp.columns

Index(['name', 'geo_id', 'geo_type', 'year', 'date', 'variable_code',
       'variable_label', 'variable_concept', 'annotation', 'value',
       'percent_change', 'difference', 'centroid', 'internal_point',
       'geometry'],
      dtype='object')

In [147]:
dfh.columns

Index(['name', 'geo_id', 'geo_type', 'year', 'date', 'variable_code',
       'variable_label', 'variable_concept', 'annotation', 'value',
       'percent_change', 'difference', 'centroid', 'internal_point',
       'geometry'],
      dtype='object')

In [148]:
dfp.rename(columns={'value':'pop'}, 
                 inplace=True)

In [149]:
dfh.rename(columns={'value':'households'}, 
                 inplace=True)

In [150]:
dfhi.rename(columns={'value':'income'}, 
                 inplace=True)

In [151]:
dfa.rename(columns={'value':'age'}, 
                 inplace=True)

In [152]:
dfg.rename(columns={'value':'gini'}, 
                 inplace=True)

In [153]:
dfm = pd.merge(dfp, dfh[['households','geo_id']],how='outer', on='geo_id')

In [154]:
dfm = pd.merge(dfm, dfhi[['income','geo_id']], on='geo_id')

In [155]:
dfm = pd.merge(dfm, dfg[['gini','geo_id']], on='geo_id')

In [156]:
dfm.head()

,name,geo_id,geo_type,year,date,variable_code,variable_label,variable_concept,annotation,pop,percent_change,difference,centroid,internal_point,geometry,households,income,gini
0,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4918
1,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4913
2,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4613
3,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,765.0,0.4560
4,"Census Tract 2501, Litchfield County, Connecticut",1400000US09005250100,tract,2014,2014-12-31,B00001_001E,Total,Unweighted Sample Count of the Population,NaN,446.0,NaN,NaN,POINT (-73.36014897889248 41.52086142577326),POINT (-73.36194696137824 41.5158335),"(POLYGON ((-73.40473799999999 41.53702, -73.40...",225.0,753.0,0.4918

In [157]:
dfm.columns

Index(['name', 'geo_id', 'geo_type', 'year', 'date', 'variable_code',
       'variable_label', 'variable_concept', 'annotation', 'pop',
       'percent_change', 'difference', 'centroid', 'internal_point',
       'geometry', 'households', 'income', 'gini'],
      dtype='object')

In [158]:
from linearmodels.panel import PanelOLS
from linearmodels import RandomEffects

In [159]:
year = pd.to_datetime(dfm['year'], format='%Y')

In [160]:
year = pd.Categorical(year)

In [162]:
print(year)

[2014-01-01, 2014-01-01, 2014-01-01, 2014-01-01, 2014-01-01, ..., 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-01]
Length: 13056
Categories (4, datetime64[ns]): [2014-01-01, 2015-01-01, 2016-01-01, 2017-01-01]

In [163]:
dfm = dfm.set_index(['pop', 'year'])

In [164]:
dfm.head()

                                                         name  \
pop   year
446.0 2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut

                          geo_id geo_type       date variable_code  \
pop   year
446.0 2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E

           variable_label                           variable_concept  \
pop   year
446.0 2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population

           annotation  percent_change  difference  \
pop   year
446.0 2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN

                                                centroid  \
pop   year
446.0 2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)

                                   internal_point  \
pop   year
446.0 2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)

                                                     geometry  households  \
pop   year
446.0 2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0

            income    gini
pop   year
446.0 2014   765.0  0.4918
      2014   765.0  0.4913
      2014   765.0  0.4613
      2014   765.0  0.4560
      2014   753.0  0.4918

In [165]:
dfm['year'] = year

In [166]:
dfm.head()

                                                         name  \
pop   year
446.0 2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut
      2014  Census Tract 2501, Litchfield County, Connecticut

                          geo_id geo_type       date variable_code  \
pop   year
446.0 2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E
      2014  1400000US09005250100    tract 2014-12-31   B00001_001E

           variable_label                           variable_concept  \
pop   year
446.0 2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population
      2014          Total  Unweighted Sample Count of the Population

           annotation  percent_change  difference  \
pop   year
446.0 2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN
      2014        NaN             NaN         NaN

                                                centroid  \
pop   year
446.0 2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)
      2014  POINT (-73.36014897889248 41.52086142577326)

                                   internal_point  \
pop   year
446.0 2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)
      2014  POINT (-73.36194696137824 41.5158335)

                                                     geometry  households  \
pop   year
446.0 2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0
      2014  (POLYGON ((-73.40473799999999 41.53702, -73.40...       225.0

            income    gini       year
pop   year
446.0 2014   765.0  0.4918 2014-01-01
      2014   765.0  0.4913 2014-01-01
      2014   765.0  0.4613 2014-01-01
      2014   765.0  0.4560 2014-01-01
      2014   753.0  0.4918 2014-01-01

In [167]:

from linearmodels.panel import PooledOLS
import statsmodels.api as sm

In [169]:
exog_vars = ['households','income', 'year']
exog = sm.add_constant(dfm[exog_vars])

/home/pak348/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [171]:
mod = PooledOLS(dfm.gini, exog)
pooled_res = mod.fit()
print(pooled_res)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                   gini   R-squared:                        1.0000
Estimator:                  PooledOLS   R-squared (Between):              1.0000
No. Observations:               13056   R-squared (Within):               1.0000
Date:                Mon, Oct 28 2019   R-squared (Overall):              1.0000
Time:                        11:39:03   Log-likelihood                 4.494e+05
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.123e+32
Entities:                         154   P-value                           0.0000
Avg Obs:                       84.779   Distribution:                 F(6,13049)
Min Obs:                       64.000
Max Obs:                       256.00   F-statistic (robust):          1.123e+32
                                        P-value                           0.0000
Time periods:                       4   Distribution:                 F(6,13049)
Avg Obs:                       3264.0
Min Obs:                       3264.0
Max Obs:                       3264.0

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
const                     1.914e-16  2.017e-17     9.4882     0.0000   1.519e-16   2.309e-16
households                9.216e-19  5.205e-20     17.704     0.0000   8.195e-19   1.024e-18
income                    5.421e-20  4.373e-21     12.395     0.0000   4.564e-20   6.278e-20
gini                         1.0000  4.201e-17   2.38e+16     0.0000      1.0000      1.0000
year.2015-01-01 00:00:00 -2.555e-16  6.762e-18    -37.789     0.0000  -2.688e-16  -2.423e-16
year.2016-01-01 00:00:00 -1.445e-16  6.762e-18    -21.372     0.0000  -1.578e-16  -1.313e-16
year.2017-01-01 00:00:00 -8.902e-17  6.762e-18    -13.164     0.0000  -1.023e-16  -7.576e-17
============================================================================================

In [13]:
mod = PanelOLS(dfp.value, dfh.value, entity_effects=True)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

ValueError: Series can only be used with a 2-level MultiIndex