In [1]:
#import libraries from Carto.
from cartoframes.auth import set_default_credentials
from cartoframes.viz import Map, Layer
import cartoframes
cartoframes.__version__
#from cartoframes.viz.helpers import color_continuous_layer
import pandas as pd
import geopandas as gpd
import requests
import json
from autocensus import Query #Library from Socrata to gather ACS Data
from cartoframes.data.services import Geocoding
#import censusdata
#set_default_credentials('creds_usignite.json')
set_default_credentials(
    base_url='https://usignite-admin.carto.com/',
    api_key='81c922dc336bd82103d92a768816a4567c444909'
)

from cartoframes.data.observatory import Catalog, Variable, Geography, Dataset

In [2]:
import numpy as np

from linearmodels import PanelOLS
from linearmodels import RandomEffects
import ipywidgets as widgets
from ipywidgets import Output, Tab
from IPython.display import clear_output
from cartoframes.data.services import Isolines
from cartoframes.data.observatory import Variable
from cartoframes.data.observatory import Enrichment
from cartoframes.data.observatory import Catalog

In [3]:
from cartoframes import read_carto

In [4]:
import geopandas as gp

In [5]:
mastercard1 = read_carto("SELECT * FROM mc_portland_mastercard_mrli_daily_sample where geoid like '0607%'")

In [6]:
mastercard = read_carto("SELECT * FROM mc_portland_mastercard_mrli_daily_sample")

In [7]:
len(mastercard)

46833

In [8]:
mastercard.columns

Index(['cartodb_id', 'the_geom', 'fid', 'geoid', 'do_date', 'industry',
       'segment', 'geo_type', 'txn_amt', 'txn_cnt', 'acct_cnt', 'avg_ticket',
       'avg_freq', 'avg_spend_amt'],
      dtype='object')

In [9]:
mastercard.head(100)

,cartodb_id,the_geom,fid,geoid,do_date,industry,segment,geo_type,txn_amt,txn_cnt,acct_cnt,avg_ticket,avg_freq,avg_spend_amt
0,1,"MULTIPOLYGON (((-122.65368 45.51221, -122.6496...",17,410510011012,2020-01-20,eap,i,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
1,2,"MULTIPOLYGON (((-122.59943 45.50439, -122.5994...",49,410510007014,2020-01-30,aut,o,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
2,3,"MULTIPOLYGON (((-122.61254 45.51483, -122.6124...",51,410510015003,2020-01-25,ret,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
3,4,"MULTIPOLYGON (((-122.63657 45.49612, -122.6366...",93,410510009022,2020-01-27,eap,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
4,5,"MULTIPOLYGON (((-122.59943 45.50439, -122.5994...",94,410510007014,2020-01-31,ret,i,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
5,6,"MULTIPOLYGON (((-122.64208 45.50196, -122.6422...",177,410510010002,2020-01-21,eap,o,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
6,7,"MULTIPOLYGON (((-122.59140 45.53036, -122.5933...",179,410510017016,2020-01-24,ret,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
7,8,"MULTIPOLYGON (((-122.64960 45.51505, -122.6425...",220,410510012014,2020-01-20,ret,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
8,9,"MULTIPOLYGON (((-122.58682 45.52284, -122.5790...",249,410510017013,2020-01-25,ret,o,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
9,10,"MULTIPOLYGON (((-122.69642 45.52555, -122.6923...",299,410510048003,2020-01-29,ret,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
10,11,"MULTIPOLYGON (((-122.63475 45.50953, -122.6347...",309,410510013023,2020-01-23,eap,i,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
11,12,"MULTIPOLYGON (((-122.63475 45.50953, -122.6347...",310,410510013023,2020-01-27,ret,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
12,13,"MULTIPOLYGON (((-122.62297 45.53234, -122.6229...",311,410510019001,2020-01-31,eap,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
13,14,"MULTIPOLYGON (((-122.64960 45.51505, -122.6425...",322,410510012014,2020-01-21,ret,o,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
14,15,"MULTIPOLYGON (((-122.63962 45.49794, -122.6375...",323,410510009013,2020-01-26,eap,i,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
15,16,"MULTIPOLYGON (((-122.63475 45.50953, -122.6347...",385,410510013023,2020-01-26,eap,d,p,629.61,269.66,272.11,29.412857,14.262857,29.440000
16,17,"MULTIPOLYGON (((-122.61778 45.51656, -122.6161...",421,410510018022,2020-01-29,eap,d,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
17,18,"MULTIPOLYGON (((-122.62297 45.53234, -122.6229...",435,410510019001,2020-01-20,eap,d,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
18,19,"MULTIPOLYGON (((-122.69642 45.52555, -122.6923...",436,410510048003,2020-01-21,eap,o,c,376.74,297.55,298.32,69.583333,67.806667,70.736667
19,20,"MULTIPOLYGON (((-122.64208 45.50196, -122.6422...",471,410510010002,2020-01-24,eap,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
20,21,"MULTIPOLYGON (((-122.63163 45.52686, -122.6316...",499,410510019004,2020-01-24,eap,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
21,22,"MULTIPOLYGON (((-122.58682 45.52284, -122.5790...",500,410510017013,2020-01-24,eap,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
22,23,"MULTIPOLYGON (((-122.59943 45.50439, -122.5994...",511,410510007014,2020-01-26,aut,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
23,24,"MULTIPOLYGON (((-122.69184 45.51528, -122.6907...",512,410510055002,2020-01-21,eap,d,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
24,25,"MULTIPOLYGON (((-122.59118 45.49567, -122.5911...",525,410510007022,2020-01-30,eap,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
25,26,"MULTIPOLYGON (((-122.57906 45.52278, -122.5739...",527,410510017022,2020-01-30,eap,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
26,27,"MULTIPOLYGON (((-122.64547 45.52574, -122.6454...",537,410510020005,2020-01-27,ret,o,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
27,28,"MULTIPOLYGON (((-122.60873 45.47999, -122.6087...",538,410510004023,2020-01-26,eap,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
28,29,"MULTIPOLYGON (((-122.64547 45.52574, -122.6454...",550,410510020005,2020-01-19,ret,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
29,30,"MULTIPOLYGON (((-122.69642 45.52555, -122.6923...",560,410510048003,2020-01-28,eap,d,p,270.31,295.75,279.53,26.866667,35.526667,28.710000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,"MULTIPOLYGON (((-122.59118 45.49567, -122.5911...",1442,410510007022,2020-01-28,ret,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
71,72,"MULTIPOLYGON (((-122.61616 45.50194, -122.6163...",1443,410510008013,2020-01-23,ret,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
72,73,"MULTIPOLYGON (((-122.67866 45.49668, -122.6783...",1466,410510059004,2020-01-29,eap,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
73,74,"MULTIPOLYGON (((-122.66055 45.49985, -122.6600...",1467,410510010005,2020-01-23,eap,o,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
74,75,"MULTIPOLYGON (((-122.59943 45.50439, -122.5994...",1468,410510007014,2020-01-22,aut,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
75,76,"MULTIPOLYGON (((-122.63150 45.49813, -122.6315...",1477,410510009012,2020-01-25,ret,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
76,77,"MULTIPOLYGON (((-122.63479 45.51923, -122.6347...",1481,410510013014,2020-01-21,eap,o,p,453.10,229.79,230.25,29.156667,16.758333,29.396667
77,78,"MULTIPOLYGON (((-122.59797 45.49013, -122.5954...",1498,410510005025,2020-01-25,ret,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
78,79,"MULTIPOLYGON (((-122.69642 45.52555, -122.6923...",1538,410510048003,2020-01-27,eap,d,m,258.37,279.75,278.85,27.726667,33.763333,28.150000
79,80,"MULTIPOLYGON (((-122.61778 45.51656, -122.6161...",1569,410510018022,2020-01-22,eap,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
80,81,"MULTIPOLYGON (((-122.63725 45.52359, -122.6370...",1571,410510020002,2020-01-23,eap,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
81,82,"MULTIPOLYGON (((-122.61712 45.50528, -122.6161...",1572,410510014004,2020-01-30,ret,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
82,83,"MULTIPOLYGON (((-122.69642 45.52555, -122.6923...",1586,410510048003,2020-01-27,eap,i,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
83,84,"MULTIPOLYGON (((-122.59118 45.49567, -122.5911...",1647,410510007022,2020-01-23,eap,i,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
84,85,"MULTIPOLYGON (((-122.63150 45.49813, -122.6315...",1667,410510009012,2020-01-24,ret,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
85,86,"MULTIPOLYGON (((-122.58472 45.49714, -122.5847...",1669,410510007021,2020-01-31,ret,d,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
86,87,"MULTIPOLYGON (((-122.62287 45.52600, -122.6230...",1682,410510019002,2020-01-31,aut,d,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
87,88,"MULTIPOLYGON (((-122.63962 45.49794, -122.6375...",1693,410510009013,2020-01-19,ret,o,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
88,89,"MULTIPOLYGON (((-122.63479 45.51923, -122.6347...",1705,410510013014,2020-01-23,eap,i,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
89,90,"MULTIPOLYGON (((-122.62570 45.49023, -122.6256...",1729,410510003011,2020-01-26,ret,d,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
90,91,"MULTIPOLYGON (((-122.69633 45.52331, -122.6953...",1737,410510048002,2020-01-24,ret,i,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
91,92,"MULTIPOLYGON (((-122.58721 45.53360, -122.5867...",1760,410510017011,2020-01-19,eap,o,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
92,93,"MULTIPOLYGON (((-122.65151 45.53361, -122.6504...",1761,410510024022,2020-01-25,eap,d,p,560.23,465.71,465.80,21.216000,20.144000,21.424000
93,94,"MULTIPOLYGON (((-122.60676 45.51424, -122.6067...",1791,410510015001,2020-01-30,ret,d,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
94,95,"MULTIPOLYGON (((-122.69642 45.52555, -122.6923...",1794,410510048003,2020-01-28,eap,o,c,144.38,155.44,149.28,25.473333,35.393333,27.086667
95,96,"MULTIPOLYGON (((-122.64960 45.51505, -122.6425...",1832,410510012014,2020-01-29,eap,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
96,97,"MULTIPOLYGON (((-122.60873 45.47999, -122.6087...",1887,410510004023,2020-01-19,ret,d,m,0.00,0.00,0.00,0.000000,0.000000,0.000000
97,98,"MULTIPOLYGON (((-122.57906 45.52278, -122.5739...",1926,410510017022,2020-01-31,eap,o,p,0.00,0.00,0.00,0.000000,0.000000,0.000000
98,99,"MULTIPOLYGON (((-122.58886 45.50539, -122.5853...",1942,410510016013,2020-01-27,eap,o,c,0.00,0.00,0.00,0.000000,0.000000,0.000000
99,100,"MULTIPOLYGON (((-122.61778 45.51656, -122.6161...",1966,410510018022,2020-01-25,ret,o,p,0.00,0.00,0.00,0.000000,0.000000,0.000000

In [10]:
#mastercard=mastercard.groupby(['geoid','industry'], as_index=False)[['txn_amt', 'txn_cnt', 'acct_cnt', 'avg_ticket',
#       'avg_freq', 'avg_spend_amt']].mean()

In [11]:
mastercard.head()

,cartodb_id,the_geom,fid,geoid,do_date,industry,segment,geo_type,txn_amt,txn_cnt,acct_cnt,avg_ticket,avg_freq,avg_spend_amt
0,1,"MULTIPOLYGON (((-122.65368 45.51221, -122.6496...",17,410510011012,2020-01-20,eap,i,p,0.0,0.0,0.0,0.0,0.0,0.0
1,2,"MULTIPOLYGON (((-122.59943 45.50439, -122.5994...",49,410510007014,2020-01-30,aut,o,p,0.0,0.0,0.0,0.0,0.0,0.0
2,3,"MULTIPOLYGON (((-122.61254 45.51483, -122.6124...",51,410510015003,2020-01-25,ret,d,m,0.0,0.0,0.0,0.0,0.0,0.0
3,4,"MULTIPOLYGON (((-122.63657 45.49612, -122.6366...",93,410510009022,2020-01-27,eap,o,m,0.0,0.0,0.0,0.0,0.0,0.0
4,5,"MULTIPOLYGON (((-122.59943 45.50439, -122.5994...",94,410510007014,2020-01-31,ret,i,m,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
mastercard['industry'].unique()

array(['eap', 'aut', 'ret', 'gro', 'app', 'acc'], dtype=object)

In [13]:
###dataset metadata methods, geo coverage,

In [14]:
industry=['eap', 'aut', 'ret', 'gro', 'app', 'acc']

In [15]:
mastercardlist=[]

In [16]:
for i in industry:
    temp=mastercard[mastercard['industry']==i]
    t1='txn_amt_'+i
    t2='txn_cnt_'+i
    t3='acct_cnt_'+i
    t4='avg_ticket_'+i
    t5='avg_freq_'+i
    t6='avg_spend_amt_'+i
    
    temp.columns=['cartodb_id', 'the_geom', 'fid', 'geoid', 'do_date', 'industry',
       'segment', 'geo_type', t1, t2, t3,t4,
       t5, t6]
    temp=temp.drop(columns=['cartodb_id', 'the_geom'])
    temp=temp.groupby('geoid', as_index=False)[[t1, t2, t3,t4,t5, t6]].mean()
    mastercardlist.append(temp)

In [17]:
#geom_coverage()
#https://carto.com/developers/cartoframes/examples/#example-discover-a-dataset
#

In [18]:
mastercardlist[0]

,geoid,txn_amt_eap,txn_cnt_eap,acct_cnt_eap,avg_ticket_eap,avg_freq_eap,avg_spend_amt_eap
0,410510001001,232.217374,195.095556,200.231515,9.321758,8.971195,9.191242
1,410510002001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,410510002002,232.217374,195.095556,200.231515,13.050631,12.541800,12.879455
3,410510003012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,410510003022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,410510004012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,410510004013,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,410510004021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,410510004022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,410510004023,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,410510005011,17.388095,22.812262,23.361310,4.803363,7.023333,4.732679
11,410510005012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,410510005014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,410510005021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,410510005022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,410510005023,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,410510005024,17.388095,22.812262,23.361310,4.803363,7.023333,4.732679
17,410510005025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,410510006014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,410510006024,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,410510007011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,410510007012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,410510007013,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,410510007021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,410510007022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,410510007023,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,410510007024,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,410510008011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,410510008012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,410510008013,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
136,410510052001,1755.990940,728.067949,740.627094,33.755257,16.421183,33.664406
137,410510052002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
138,410510052003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
139,410510052004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
140,410510055002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
141,410510056001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
142,410510056002,144.107265,334.421282,340.158205,3.710199,9.347507,3.694701
143,410510056003,112.108205,267.243504,271.302222,2.217997,5.857007,2.218716
144,410510056004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
145,410510057001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
146,410510057002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
147,410510057003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
148,410510058001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
149,410510058002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
150,410510058003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
151,410510058004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
152,410510059001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
153,410510059002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
154,410510059003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
155,410510059004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
156,410510060011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
157,410510060012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
158,410510060021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
159,410510061002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
160,410510067021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
161,410510083011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
162,410510083012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
163,410510106001,3876.226239,2303.767607,2325.676239,19.177939,12.641912,19.244866
164,410510106002,531.620342,266.612051,272.156923,7.160650,4.050306,7.101128
165,410510106003,2094.999316,1887.137863,1903.615812,13.918309,13.472825,14.001839

In [83]:
len(mastercardlist)

6

In [94]:
mastercardlist[1]

,geoid,txn_amt_aut,txn_cnt_aut,acct_cnt_aut,avg_ticket_aut,avg_freq_aut,avg_spend_amt_aut
0,410510001001,0.0,0.0,0.0,0.0,0.0,0.0
1,410510002001,0.0,0.0,0.0,0.0,0.0,0.0
2,410510002002,0.0,0.0,0.0,0.0,0.0,0.0
3,410510003012,0.0,0.0,0.0,0.0,0.0,0.0
4,410510003022,0.0,0.0,0.0,0.0,0.0,0.0
5,410510004013,0.0,0.0,0.0,0.0,0.0,0.0
6,410510004021,0.0,0.0,0.0,0.0,0.0,0.0
7,410510005011,0.0,0.0,0.0,0.0,0.0,0.0
8,410510005021,0.0,0.0,0.0,0.0,0.0,0.0
9,410510005024,0.0,0.0,0.0,0.0,0.0,0.0
10,410510006014,0.0,0.0,0.0,0.0,0.0,0.0
11,410510006024,0.0,0.0,0.0,0.0,0.0,0.0
12,410510007013,0.0,0.0,0.0,0.0,0.0,0.0
13,410510007014,0.0,0.0,0.0,0.0,0.0,0.0
14,410510007024,0.0,0.0,0.0,0.0,0.0,0.0
15,410510008011,0.0,0.0,0.0,0.0,0.0,0.0
16,410510008014,0.0,0.0,0.0,0.0,0.0,0.0
17,410510008022,0.0,0.0,0.0,0.0,0.0,0.0
18,410510008023,0.0,0.0,0.0,0.0,0.0,0.0
19,410510008024,0.0,0.0,0.0,0.0,0.0,0.0
20,410510009011,0.0,0.0,0.0,0.0,0.0,0.0
21,410510009021,0.0,0.0,0.0,0.0,0.0,0.0
22,410510009023,0.0,0.0,0.0,0.0,0.0,0.0
23,410510010001,0.0,0.0,0.0,0.0,0.0,0.0
24,410510010003,0.0,0.0,0.0,0.0,0.0,0.0
25,410510010004,0.0,0.0,0.0,0.0,0.0,0.0
26,410510011011,0.0,0.0,0.0,0.0,0.0,0.0
27,410510011021,0.0,0.0,0.0,0.0,0.0,0.0
28,410510012013,0.0,0.0,0.0,0.0,0.0,0.0
29,410510012021,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
58,410510025021,0.0,0.0,0.0,0.0,0.0,0.0
59,410510025023,0.0,0.0,0.0,0.0,0.0,0.0
60,410510025024,0.0,0.0,0.0,0.0,0.0,0.0
61,410510026003,0.0,0.0,0.0,0.0,0.0,0.0
62,410510027021,0.0,0.0,0.0,0.0,0.0,0.0
63,410510027022,0.0,0.0,0.0,0.0,0.0,0.0
64,410510029032,0.0,0.0,0.0,0.0,0.0,0.0
65,410510046022,0.0,0.0,0.0,0.0,0.0,0.0
66,410510048001,0.0,0.0,0.0,0.0,0.0,0.0
67,410510049001,0.0,0.0,0.0,0.0,0.0,0.0
68,410510050001,0.0,0.0,0.0,0.0,0.0,0.0
69,410510051002,0.0,0.0,0.0,0.0,0.0,0.0
70,410510056001,0.0,0.0,0.0,0.0,0.0,0.0
71,410510056003,0.0,0.0,0.0,0.0,0.0,0.0
72,410510057001,0.0,0.0,0.0,0.0,0.0,0.0
73,410510057002,0.0,0.0,0.0,0.0,0.0,0.0
74,410510058002,0.0,0.0,0.0,0.0,0.0,0.0
75,410510058004,0.0,0.0,0.0,0.0,0.0,0.0
76,410510059001,0.0,0.0,0.0,0.0,0.0,0.0
77,410510059002,0.0,0.0,0.0,0.0,0.0,0.0
78,410510059003,0.0,0.0,0.0,0.0,0.0,0.0
79,410510060011,0.0,0.0,0.0,0.0,0.0,0.0
80,410510060021,0.0,0.0,0.0,0.0,0.0,0.0
81,410510061002,0.0,0.0,0.0,0.0,0.0,0.0
82,410510067021,0.0,0.0,0.0,0.0,0.0,0.0
83,410510083011,0.0,0.0,0.0,0.0,0.0,0.0
84,410510083012,0.0,0.0,0.0,0.0,0.0,0.0
85,410510106001,0.0,0.0,0.0,0.0,0.0,0.0
86,410510106002,0.0,0.0,0.0,0.0,0.0,0.0
87,410510106003,0.0,0.0,0.0,0.0,0.0,0.0

In [84]:

for i in range(len(mastercardlist)):
    t1='txn_amt_'+industry[i]
    t2='txn_cnt_'+industry[i]
    t3='acct_cnt_'+industry[i]
    t4='avg_ticket_'+industry[i]
    t5='avg_freq_'+industry[i]
    t6='avg_spend_amt_'+industry[i]
    if i==0:
        temp=mastercardlist[i]
    else:
        temp = pd.merge(temp, mastercardlist[i][['geoid','fid',t1, t2, t3,t4,t5, t6]], on=['geoid','fid'])

In [85]:
temp.head()

Empty GeoDataFrame
Columns: [do_date, industry, segment, geo_type, txn_amt_eap, txn_cnt_eap, acct_cnt_eap, avg_ticket_eap, avg_freq_eap, avg_spend_amt_eap, txn_amt_aut, txn_cnt_aut, acct_cnt_aut, avg_ticket_aut, avg_freq_aut, avg_spend_amt_aut, txn_amt_ret, txn_cnt_ret, acct_cnt_ret, avg_ticket_ret, avg_freq_ret, avg_spend_amt_ret, txn_amt_gro, txn_cnt_gro, acct_cnt_gro, avg_ticket_gro, avg_freq_gro, avg_spend_amt_gro, txn_amt_app, txn_cnt_app, acct_cnt_app, avg_ticket_app, avg_freq_app, avg_spend_amt_app, geoid, fid, txn_amt_acc, txn_cnt_acc, acct_cnt_acc, avg_ticket_acc, avg_freq_acc, avg_spend_amt_acc]
Index: []

[0 rows x 42 columns]

In [35]:
mastercardlist[0].columns

Index(['cartodb_id', 'the_geom', 'fid', 'geoid', 'do_date', 'industry',
       'segment', 'geo_type', 'txn_amt_eap', 'txn_cnt_eap', 'acct_cnt_eap',
       'avg_ticket_eap', 'avg_freq_eap', 'avg_spend_amt_eap'],
      dtype='object')

In [33]:
df=pd.read_csv("~/Downloads/city_portland.csv")

In [34]:
df.head()

,Unnamed: 0,cartodb_id,the_geom,namelsad10,aland10,awater10,intptlat10,intptlon10,dp0010001,dp0010002,...,estabratio2013,Empratio2013,estabratio2012,Empratio2012,estabratio2011,Empratio2011,estabratio2010,Empratio2010,estabratio2009,Empratio2009
0,0,54823,"MULTIPOLYGON (((-122.67809 45.56266900000014, ...",Census Tract 38.03,1231249.0,0.0,45.566302,-122.684730,3933,263,...,28.092857,638.060440,27.789560,614.934066,37.457143,1022.109890,39.163187,1037.274725,38.973626,1071.395604
1,1,54874,"MULTIPOLYGON (((-122.723153 45.47230700000006,...",Census Tract 66.01,1575238.0,0.0,45.471920,-122.733420,2513,145,...,20.483974,342.596154,20.798077,339.903846,22.727564,377.820513,22.323718,371.089744,22.233974,369.070513
2,2,54924,"MULTIPOLYGON (((-122.58001 45.46152, -122.5893...",Census Tract 86,1282152.0,3236.0,45.469339,-122.586175,4333,337,...,10.398849,140.661553,9.860978,134.630872,12.289549,206.347076,12.452541,207.976989,12.843720,216.126558
3,3,54924,"MULTIPOLYGON (((-122.58001 45.46152, -122.5893...",Census Tract 86,1282152.0,3236.0,45.469339,-122.586175,4333,337,...,20.389210,327.581888,20.745665,325.443160,31.581888,592.427746,32.116570,580.308285,31.831407,577.813102
4,4,54795,"MULTIPOLYGON (((-122.579016 45.55542500000013,...",Census Tract 29.01,1536178.0,0.0,45.551447,-122.592739,4428,312,...,42.773733,915.310493,40.640971,870.877944,48.164882,1039.721627,49.349750,1049.793005,49.468237,995.881513